### ISSUE TITLE
Ability to use data- attributes to set countTo and countFrom values

### ISSUE THREAD

**Issue by tombruijn** [tombruijn/counter.js#1]
```html
<div class="number" data-counter-to="123">0</div>
```

```js
$(".number").counter()
```

Result:
```ruby
# => <div class="number" data-counter-to="123">123</div>
```

**Comment by a3020** [comment]
If you put this on line [116](https://github.com/tombruijn/counter.js/blob/master/js/counter.js#L116) it uses the data attribute 

```javascript
options.countTo = $(this).attr('data-count-to') ? $(this).attr('data-count-to') : options.countTo;
```

**Comment by tombruijn** [comment]
Closed by d3be63e280e123e976d9ac384fb837230895dabe

**Comment by jimmyadaro** [comment]
@tombruijn This seems to not work anymore, could you please give it a look?

**Comment by tombruijn** [comment]
I don't know why it wouldn't work, it's the very last thing that was added to the library.

But it's a 3 year old project, I'm sure there are better ways to do this now.
