### ISSUE TITLE
Floating number

### ISSUE THREAD

**Issue by sorenbryder** [tombruijn/counter.js#10]
Is there any reason not to use:
givenNumber = parseFloat(this.element.innerHTML);

instead of:
givenNumber = parseInt(this.element.innerHTML);

The parseInt just seems to limit the usability of the plugin.

**Comment by tombruijn** [comment]
Hi @sorenbryder,

It's been a while since I worked on this.. Or used it myself.

But yes, I guess it could use parseFloat instead of parseInt. Updated it
